### ISSUE TITLE
openasar setting under advanced

### ISSUE THREAD

**Issue by speedlorenzo12** [GooseMod/OpenAsar#179]
openasar after the advanced setting is not present if discord has inserted a language other than English

windows 11

**Comment by Julienraptor02** [comment]
It would be very nice if this could get fixed due to multiple issues
- Not working with different languages than english create confusion for all people which don't use english which is a non-negligible amount of people
- Having to click on OpenAsar Nightly at the bottom in the versions is very unexpected behavior
- Clicking the version text cause it to being copied into the clipboard, which mean that if you want to paste smth in OpenAsar theme, you have to remember to copy the text after having opened the settings
And personally in my opinion, OpenAsar being under User Settings is a smaller problem than those
Anyway i'm on my way to make a patch to make it work on all languages by not relying on any localized text

**Comment by speedlorenzo12** [comment]
I have a feeling that the update is not working since I can't get the section in any language anymore (both English and my language)

**Comment by Julienraptor02** [comment]
i'm looking into it rn if you are on the discord, you can come and help
it's very weird tho that even the english method is broken...
